# Generated by Django 5.2.12 on 2026-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_verification',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email_verifie',
            field=models.BooleanField(default=False),
        ),
    ]
