# Generated by Django 5.2.12 on 2026-03-09 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_utilisateur_code_verification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('alimentaire', 'Alimentaire'), ('non_alimentaire', 'Non alimentaire')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='familles/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('alimentaire', 'Alimentaire'), ('non_alimentaire', 'Non alimentaire')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('allergenes', models.TextField(blank=True)),
                ('temperature_conservation', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('marque', models.CharField(blank=True, max_length=50)),
                ('garantie_mois', models.PositiveIntegerField(blank=True, null=True)),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptes.famille')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
