# Generated by Django 5.2.12 on 2026-03-09 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_fournisseur_entreestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortieStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('motif', models.CharField(choices=[('vente', 'Vente'), ('consommation', 'Consommation interne'), ('perte', 'Perte / Perime'), ('retour', 'Retour fournisseur'), ('autre', 'Autre')], max_length=20)),
                ('destinataire', models.CharField(blank=True, max_length=100)),
                ('date_sortie', models.DateField()),
                ('numero_reference', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='comptes.produit')),
            ],
            options={
                'verbose_name': 'Sortie stock',
                'verbose_name_plural': 'Sorties stock',
                'ordering': ['-date_sortie'],
            },
        ),
    ]
