# Generated by Django 5.2.12 on 2026-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_sortiestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='pays',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
