# Generated by Django 5.2.12 on 2026-03-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_fournisseur_pays_fournisseur_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
        migrations.AlterField(
            model_name='sortiestock',
            name='motif',
            field=models.CharField(choices=[('vente', 'Vente'), ('consommation', 'Consommation interne'), ('perte', 'Perte / Périmé'), ('retour', 'Retour fournisseur'), ('autre', 'Autre')], max_length=20),
        ),
    ]
