# Generated by Django 5.2 on 2026-03-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_utilisateur_photo_profil_alter_sortiestock_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='code_produit',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='adresse_entreprise',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone_entreprise',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
