# Generated by Django 5.2 on 2026-03-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_add_code_produit_and_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='supprime',
            field=models.BooleanField(default=False),
        ),
    ]
